name: Dashboard e2e testing

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  cypress:
    defaults:
      run:
        working-directory: ./

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm install

      - run: npm run build
        env:
          NODE_ENV: production

      - name: Run project locally
        run: |
          npm install serve
          $(npm bin)/serve dist -s -p 8080 &
        
      - name: Run tests
        uses: cypress-io/github-action@v6
        with:	
          browser: chrome