name: Dashboard e2e testing

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  cypress:
    defaults:
      run:
        working-directory: ./

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm install

      - run: npm run build
        env:
          NODE_ENV: production
        
      - name: Run tests
        uses: cypress-io/github-action@v6
        with:	
          browser: chrome
          start: npm run serve
          wait-on: 'http://localhost:8080'